import React from 'react';
import { AlertTriangle, CheckCircle } from 'lucide-react';

interface Props {
  onAccept: () => void;
}

const DisclaimerModal: React.FC<Props> = ({ onAccept }) => {
  return (
    <div className="fixed inset-0 z-[100] bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden animate-fade-in-up">
        <div className="bg-amber-50 p-6 border-b border-amber-100 flex items-start gap-4">
          <div className="bg-amber-100 p-2 rounded-full shrink-0">
            <AlertTriangle className="w-6 h-6 text-amber-600" />
          </div>
          <div>
            <h2 className="text-lg font-bold text-amber-900">Clinical Disclaimer</h2>
            <p className="text-sm text-amber-800 mt-1">Please read carefully before proceeding.</p>
          </div>
        </div>
        
        <div className="p-6 space-y-4 text-slate-600 text-sm leading-relaxed">
          <p>
            <strong>This is a clinical triage assistant powered by Google's Gemini models. Your conversational assistant is Eli.</strong>
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li>Eli provides information based on established clinical guidelines but <strong>does not provide a medical diagnosis</strong>.</li>
            <li>In case of a medical emergency, <strong>call emergency services immediately</strong>. Do not rely on Eli for life-saving interventions.</li>
            <li>All assessments generated by Eli must be reviewed by a human medical officer.</li>
            <li>Data is handled in accordance with HIPAA data privacy principles for JC Juneja Hospital.</li>
          </ul>
        </div>

        <div className="p-6 bg-slate-50 border-t border-slate-100 flex justify-end">
          <button 
            onClick={onAccept}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2.5 rounded-lg font-medium transition-colors shadow-lg shadow-indigo-600/20"
          >
            <CheckCircle className="w-4 h-4" />
            Accept & Continue
          </button>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerModal;